# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nrxIBr5_DTLcEa3jJfdRzzHhhjO5mduZ
"""

# importing libraries
import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Title for the web app
st.title("Heart Disease Prediction App")
st.write("Please upload your test_data.csv file to see model results.")

# 1. Dataset upload option
uploaded_file = st.file_uploader("Upload CSV Data", type=["csv"])

# 2. Model selection dropdown
model_name = st.selectbox(
    "Choose a Model",
    ["Logistic Regression", "Decision Tree", "kNN", "Naive Bayes", "Random Forest"]
)

# if the user uploads a file, then do this
if uploaded_file is not None:
    # read the csv file
    df = pd.read_csv(uploaded_file)
    st.write("### Data Preview")
    st.write(df.head())

    # check if HeartDisease is in the data
    if 'HeartDisease' in df.columns:
        # get X and Y
        X = df.drop('HeartDisease', axis=1)
        Y = df['HeartDisease']

        # load the correct model using if/elif statements
        my_model = None
        if model_name == "Logistic Regression":
            my_model = joblib.load("model/logistic_regression.pkl")
        elif model_name == "Decision Tree":
            my_model = joblib.load("model/decision_tree.pkl")
        elif model_name == "kNN":
            my_model = joblib.load("model/knn.pkl")
        elif model_name == "Naive Bayes":
            my_model = joblib.load("model/naive_bayes.pkl")
        elif model_name == "Random Forest":
            my_model = joblib.load("model/random_forest.pkl")

        # make sure model loaded
        if my_model is not None:
            st.write("Model loaded successfully!")

            # predict the data
            predictions = my_model.predict(X)

            # try to get probabilities for AUC, if it fails just use predictions
            try:
                probabilities = my_model.predict_proba(X)[:, 1]
            except:
                probabilities = predictions

            # calculate all the metrics
            acc = accuracy_score(Y, predictions)
            auc = roc_auc_score(Y, probabilities)
            prec = precision_score(Y, predictions)
            rec = recall_score(Y, predictions)
            f1 = f1_score(Y, predictions)
            mcc = matthews_corrcoef(Y, predictions)

            # 3. Display evaluation metrics
            st.write("### Evaluation Metrics")
            st.write("**Accuracy:**", round(acc, 4))
            st.write("**AUC Score:**", round(auc, 4))
            st.write("**Precision:**", round(prec, 4))
            st.write("**Recall:**", round(rec, 4))
            st.write("**F1 Score:**", round(f1, 4))
            st.write("**MCC Score:**", round(mcc, 4))

            # 4. Confusion matrix and classification report
            st.write("### Confusion Matrix")
            cm = confusion_matrix(Y, predictions)
            fig = plt.figure(figsize=(4, 3))
            sns.heatmap(cm, annot=True, fmt='g')
            st.pyplot(fig)

            st.write("### Classification Report")
            report = classification_report(Y, predictions, output_dict=True)
            # convert to dataframe so it looks nice in streamlit
            report_df = pd.DataFrame(report).transpose()
            st.dataframe(report_df)

    else:
        st.write("Error: There is no HeartDisease column in the uploaded file.")
else:
    st.write("Waiting for file upload...")